services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern_backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - mern_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge
